# Generated by Django 4.2.24 on 2025-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('under_armour', 'Under Armour'), ('reebok', 'Reebok'), ('mils', 'Mils'), ('specs', 'Specs'), ('ortuseight', 'Ortuseight'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
