# Generated by Django 4.2.24 on 2025-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, default='https://media.istockphoto.com/id/1147544809/vector/no-thumbnail-image-vector-graphic.jpg?s=170667a&w=0&k=20&c=v9QBkaN6fXxy1b-wsTQ6QhHUVGLo8JMMxhUBcWzOH0A=', null=True),
        ),
    ]
