# Generated by Django 4.2.24 on 2025-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_rating_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='terjual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
