# Generated by Django 4.2.24 on 2025-09-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_terjual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='terjual',
            new_name='sold',
        ),
    ]
